# =============================================================================
# mod_times.R — Onglet Temps optimaux (+ multi-run + model prediction + summary)
# =============================================================================

mod_times_ui <- function(id) {
  ns <- NS(id)
  tagList(
    settings_bar(
      radioButtons(ns("time_unit"), "Time unit",
        choices = c("Hours" = "hours", "Days" = "days"),
        selected = "hours", inline = TRUE)
    ),
    mod_mrgsolve_ui(ns("mrgsolve")),
    uiOutput(ns("content"))
  )
}

mod_times_server <- function(id, tab_data, all_runs = reactive(list()),
                             cmt_labels = reactive(NULL),
                             ext_data = reactive(NULL),
                             ctl_lines = reactive(NULL),
                             theta_labels = reactive(NULL)) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    # -- mrgsolve sub-module (nested) ------------------------------------------
    mrg_sim <- mod_mrgsolve_server("mrgsolve",
      ext_data     = ext_data,
      tab_data     = tab_data,
      ctl_lines    = ctl_lines,
      theta_labels = theta_labels
    )

    # -- Tab effectif : tab_data() ou premier run secondaire ayant un .tab ------
    # Permet d'afficher l'onglet Temps optimaux meme si le run principal n'a
    # pas de fichier .tab (ex : run A = evaluation, run B = optimisation).
    effective_tab_data <- reactive({
      tab <- tab_data()
      if (!is.null(tab)) return(tab)
      for (r in all_runs()) {
        if (!is.null(r$tab_data)) return(r$tab_data)
      }
      NULL
    })

    # -- Detection robust design (multi-table) ---------------------------------
    is_robust <- reactive({
      tab <- effective_tab_data()
      if (is.null(tab)) return(FALSE)
      "table_no" %in% names(tab) && n_distinct(tab$table_no) > 1L
    })

    # Table 1 uniquement (pour courbe predite + table d'affichage)
    tab_single <- reactive({
      tab <- effective_tab_data()
      req(tab)
      if (is_robust()) filter(tab, table_no == 1L) else tab
    })

    # Helper: agregation robuste pour un seul run (tab = data.frame brut)
    .robust_summary_one <- function(tab) {
      obs <- tab
      if ("EVID" %in% names(obs)) obs <- dplyr::filter(obs, EVID == 0)
      if (!"TSTRAT" %in% names(obs)) {
        obs <- obs |>
          dplyr::group_by(table_no) |>
          dplyr::mutate(TSTRAT = dplyr::row_number()) |>
          dplyr::ungroup()
      }
      obs <- obs |>
        dplyr::group_by(table_no, TSTRAT) |>
        dplyr::mutate(obs_idx = dplyr::row_number()) |>
        dplyr::ungroup()
      obs |>
        dplyr::group_by(TSTRAT, obs_idx) |>
        dplyr::summarise(
          N_subprob = dplyr::n_distinct(table_no),
          P10       = round(quantile(TIME, 0.10, na.rm = TRUE), 2),
          Median    = round(median(TIME,          na.rm = TRUE), 2),
          P90       = round(quantile(TIME, 0.90,  na.rm = TRUE), 2),
          .groups   = "drop"
        ) |>
        dplyr::arrange(TSTRAT, obs_idx) |>
        dplyr::rename(Stratum = TSTRAT, Obs = obs_idx, N = N_subprob)
    }

    # Agregation robuste partagee (renderDT + downloadHandler)
    # Multi-run : long format avec colonne Run en tete
    robust_summary <- reactive({
      runs <- all_runs()
      if (length(runs) <= 1L) {
        tab <- tab_data(); req(tab)
        return(.robust_summary_one(tab))
      }
      result <- purrr::imap(runs, function(r, rid) {
        if (is.null(r$tab_data)) return(NULL)
        tab <- r$tab_data
        if (!("table_no" %in% names(tab)) || dplyr::n_distinct(tab$table_no) <= 1L)
          return(NULL)
        .robust_summary_one(tab) |>
          dplyr::mutate(Run = r$name %||% rid, .before = 1)
      }) |> dplyr::bind_rows()
      req(nrow(result) > 0L)
      result
    })

    # -- UI dynamique ----------------------------------------------------------
    output$content <- renderUI({
      tab <- effective_tab_data()

      if (is.null(tab)) {
        return(div(class = "alert alert-info", style = "border-radius:10px; margin:16px 0;",
          tags$strong("Optimal Times"),
          tags$p(style = "margin:6px 0 0;",
            "Available when:",
            tags$ul(style = "margin:4px 0;",
              tags$li("A ", tags$code(".tab"), " file is loaded (generated by ",
                      tags$code("$TABLE"), " in the control file)"),
              tags$li("The .tab contains optimized sampling times (",
                      tags$code("TIME"), ", ", tags$code("TSTRAT"), ")")
            )
          )
        ))
      }

      robust_banner <- if (is_robust()) {
        n_tabs <- n_distinct(tab$table_no)
        div(class = "alert alert-info",
            style = "border-radius:8px; margin-bottom:12px; padding:10px 14px;",
          tags$strong(paste0("Robust design detected (", n_tabs, " sub-problems)")),
          tags$p(style = "margin:4px 0 0; font-size:0.9em;",
            "The optimal times distribution is computed over all prior realizations. ",
            "The predicted curve uses only the first realization."
          )
        )
      } else {
        NULL
      }

      if (is_robust()) {
        # Design robuste : pas de courbe predite, boxplot central + table resume
        tagList(
          robust_banner,
          fluidRow(
            column(8,
              div(class = "plot-card",
                p(class = "section-title",
                  "Optimal times distribution by stratum (robust design)"),
                plotOutput(ns("gantt"), height = "420px"),
                plot_export_ui(ns, "gantt_export", default_fname = "robust_times_dist")
              )
            ),
            column(4,
              div(class = "param-table-wrap",
                p(class = "section-title", "Summary statistics (P10 / median / P90)"),
                DTOutput(ns("times_table"))
              )
            )
          )
        )
      } else {
        tagList(
          fluidRow(
            column(12,
              div(class = "plot-card",
                p(class = "section-title", "Predicted curve and sampling points"),
                plotOutput(ns("prediction"), height = "400px"),
                plot_export_ui(ns, "pred_export", default_fname = "prediction_plot")
              )
            )
          ),
          br(),
          fluidRow(
            column(12,
              div(class = "param-table-wrap",
                p(class = "section-title", "Optimal times data"),
                DTOutput(ns("times_table"))
              )
            )
          )
        )
      }
    })

    # -- Courbe predite (reactive for export) ------------------------------------
    pred_plot <- reactive({
      runs <- all_runs()
      tu <- input$time_unit %||% "hours"

      # mrgsolve smooth plot: if simulation is available, use it
      if (!is.null(mrg_sim) && isTRUE(mrg_sim$is_available())) {
        req(tab_single())
        # Get compare points from second run (CTP) if available
        ctp_points <- NULL
        if (length(runs) > 1L) {
          run_keys <- names(runs)
          for (rk in run_keys[-1]) {
            if (!is.null(runs[[rk]]$tab_data)) {
              ctp_points <- runs[[rk]]$tab_data
              break
            }
          }
        }
        return(plot_pk_profile(
          sim_data       = mrg_sim$sim_data(),
          obs_points     = tab_single(),
          dose_times     = mrg_sim$dose_times(),
          time_unit      = tu,
          cmt_labels     = cmt_labels(),
          compare_points = ctp_points
        ))
      }

      if (length(runs) <= 1L) {
        req(tab_single())
        return(plot_model_prediction(tab_single(), time_unit = tu))
      }

      # Multi-run : overlay des courbes predites par run
      pred_cols_used <- character(0)
      combined <- purrr::imap(runs, function(r, rid) {
        if (is.null(r$tab_data)) return(NULL)
        tab <- r$tab_data
        if ("table_no" %in% names(tab) && dplyr::n_distinct(tab$table_no) > 1L)
          tab <- dplyr::filter(tab, table_no == 1L)
        if ("EVID" %in% names(tab)) tab <- dplyr::filter(tab, EVID == 0)
        if (nrow(tab) == 0L) return(NULL)
        pred_col <- intersect(c("IPRED", "PRED", "DV"), names(tab))[1]
        if (is.na(pred_col)) return(NULL)
        pred_cols_used[[rid]] <<- pred_col
        tab |>
          dplyr::mutate(IPRED = .data[[pred_col]], run = rid) |>
          dplyr::select(any_of(c("TIME", "IPRED", "TSTRAT", "run")))
      }) |> dplyr::bind_rows()
      # Warn if runs use different prediction columns
      if (length(unique(pred_cols_used)) > 1L) {
        message("[mod_times] Runs use different prediction columns: ",
                paste(names(pred_cols_used), pred_cols_used,
                      sep = "=", collapse = ", "))
      }

      if (nrow(combined) == 0L) {
        req(tab_single())
        return(plot_model_prediction(tab_single()))
      }

      run_labels <- setNames(vapply(runs, function(r) r$name %||% "?", character(1L)),
                             names(runs))
      run_colors <- setNames(vapply(names(runs), run_color, character(1L)),
                             names(runs))

      ggplot(combined, aes(x = TIME, y = IPRED, color = run, group = run)) +
        geom_line(linetype = "dashed", alpha = 0.6, size = 0.8) +
        geom_point(size = 2.5, alpha = 0.9) +
        scale_color_manual(values = run_colors, labels = run_labels,
                           name = NULL) +
        .theme_design() +
        labs(
          title    = "Predictions (IPRED) at optimal sampling times",
          subtitle = "Multi-run comparison",
          x = "Time (h)", y = "IPRED",
          caption  = paste0(
            "Each point = model prediction at an optimal time",
            " | Dashes = point connections (not a continuous PK curve)"
          )
        )
    })

    output$prediction <- renderPlot({ pred_plot() }, res = 110)
    plot_export_server(input, output, session, "pred_export", pred_plot)

    # -- Gantt / distribution (reactive for export) ------------------------------
    gantt_plot <- reactive({
      tab <- effective_tab_data()
      runs <- all_runs()

      # Cas robust design : boxplot + annotations medianes + multi-run overlay
      if (is_robust()) {
        req(tab)
        obs <- tab
        if ("EVID" %in% names(obs)) obs <- filter(obs, EVID == 0)
        if (!"TSTRAT" %in% names(obs)) {
          obs <- obs |>
            dplyr::group_by(table_no) |>
            dplyr::mutate(TSTRAT = dplyr::row_number()) |>
            dplyr::ungroup()
        }
        obs <- obs |> mutate(group = factor(paste0("Stratum ", TSTRAT)))
        n_tabs <- n_distinct(tab$table_no)

        med_labels <- obs |>
          dplyr::group_by(group) |>
          dplyr::summarise(med = median(TIME), .groups = "drop")

        p <- ggplot(obs, aes(x = TIME, y = group, fill = group)) +
          geom_boxplot(alpha = 0.7, outlier.size = 0.8,
                       outlier.alpha = 0.4) +
          geom_text(data = med_labels,
                    aes(x = med, y = group,
                        label = sprintf("%.1fh", med)),
                    inherit.aes = FALSE,
                    vjust = -0.6, size = 3.2, fontface = "bold",
                    color = "#1e3a5f") +
          scale_fill_brewer(palette = "Set2", guide = "none")

        if (length(runs) > 1L) {
          comp_pts <- purrr::imap(runs[-1], function(r, rid) {
            if (is.null(r$tab_data)) return(NULL)
            comp_tab <- r$tab_data
            if ("table_no" %in% names(comp_tab) &&
                dplyr::n_distinct(comp_tab$table_no) > 1L)
              comp_tab <- dplyr::filter(comp_tab, table_no == 1L)
            if ("EVID" %in% names(comp_tab))
              comp_tab <- dplyr::filter(comp_tab, EVID == 0)
            if (nrow(comp_tab) == 0L) return(NULL)
            if (!"TSTRAT" %in% names(comp_tab))
              comp_tab$TSTRAT <- seq_len(nrow(comp_tab))
            comp_tab |>
              dplyr::mutate(group = factor(paste0("Stratum ", TSTRAT)),
                            run = rid) |>
              dplyr::select(dplyr::any_of(c("TIME", "group", "run")))
          }) |> dplyr::bind_rows()

          if (nrow(comp_pts) > 0L) {
            run_labels <- setNames(
              vapply(runs[-1], function(r) r$name %||% "?", character(1L)),
              names(runs[-1]))
            run_colors <- setNames(
              vapply(names(runs[-1]), run_color, character(1L)),
              names(runs[-1]))
            p <- p +
              geom_point(data = comp_pts,
                         aes(x = TIME, y = group, color = run),
                         inherit.aes = FALSE, size = 3, alpha = 0.85,
                         position = position_dodge(width = 0.3)) +
              scale_color_manual(values = run_colors, labels = run_labels,
                                 name = NULL)
          }
        }

        caption_txt <- paste0(
          "N = ", n_tabs,
          " prior realizations | Box = median + IQR | ",
          "Number = median")
        if (length(runs) > 1L)
          caption_txt <- paste0(caption_txt,
                                " | Colored points = comparison runs")

        return(
          p +
            labs(
              title = "Optimal times distribution by stratum",
              x     = "Time (h)",
              y     = NULL,
              caption = caption_txt
            ) +
            theme_bw(base_size = 12) +
            theme(
              panel.grid.major.y = element_blank(),
              plot.caption = element_text(size = 8, color = "#6b7280")
            )
        )
      }

      # Cas multi-run
      if (length(runs) > 1L) {
        combined <- purrr::imap(runs, function(r, rid) {
          if (is.null(r$tab_data)) return(NULL)
          obs <- r$tab_data
          if ("EVID" %in% names(obs)) obs <- filter(obs, EVID == 0)
          if (!"TSTRAT" %in% names(obs)) obs$TSTRAT <- 1
          obs |> mutate(run = rid) |>
            select(any_of(c("TSTRAT", "TIME", "run")))
        }) |> dplyr::bind_rows()
        if (nrow(combined) == 0) {
          return(plot_optimal_times(tab_single()))
        }

        combined <- combined |>
          mutate(group = factor(paste0("Stratum ", TSTRAT)))

        run_labels <- setNames(vapply(runs, function(r) r$name %||% "?", character(1L)),
                               names(runs))
        run_colors <- setNames(vapply(names(runs), run_color, character(1L)),
                               names(runs))
        return(
          ggplot(combined, aes(x = TIME, y = group,
                               color = run, shape = run)) +
            geom_point(size = 3, alpha = 0.85,
                       position = position_dodge(width = 0.4)) +
            scale_color_manual(values = run_colors, labels = run_labels,
                               name = NULL) +
            labs(title = "Sampling times -- Multi-run comparison",
                 x = "Time (h)", y = NULL,
                 caption = "Each point = optimal sampling time for this patient group (TSTRAT)") +
            theme_bw(base_size = 12) +
            theme(legend.position = "bottom",
                  panel.grid.major.y = element_blank(),
                  plot.caption = element_text(size = 8, color = "#6b7280"))
        )
      }

      NULL
    })

    output$gantt <- renderPlot({ gantt_plot() }, res = 110)
    plot_export_server(input, output, session, "gantt_export", gantt_plot)

    # -- Table -----------------------------------------------------------------
    output$times_table <- renderDT({
      tab <- effective_tab_data(); req(tab)

      if (is_robust()) {
        return(datatable(robust_summary(), rownames = FALSE,
                         class = "stripe hover compact",
                         options = list(pageLength = 30, dom = "t",
                                        scrollX = TRUE)))
      }

      # Cas normal : table des temps individuels
      obs <- tab_single()
      if ("EVID" %in% names(obs)) obs <- filter(obs, EVID == 0)

      # Elementary datasets (GROUPSIZE > 1): collapse to one row per unique
      # sampling point. All IDs within the same arm share the same design times.
      if ("ID" %in% names(obs) && dplyr::n_distinct(obs$ID) > 4L &&
          "TSTRAT" %in% names(obs)) {
        arm_sig <- obs |>
          dplyr::group_by(ID) |>
          dplyr::summarise(sig = paste(sort(unique(TSTRAT)), collapse = ","),
                           .groups = "drop")
        rep_ids <- arm_sig |>
          dplyr::group_by(sig) |>
          dplyr::slice_min(ID, n = 1L) |>
          dplyr::ungroup() |>
          dplyr::pull(ID)
        obs <- obs |> dplyr::filter(ID %in% rep_ids)
      }

      cols_show <- intersect(
        c("ID", "TSTRAT", "TMIN", "TIME", "TMAX", "IPRED", "CONC", "STRAT", "CMT"),
        names(obs)
      )
      if (length(cols_show) == 0L) {
        cols_show <- names(obs)[!names(obs) %in% c("table_no")]
      }

      obs_display <- obs |>
        select(all_of(cols_show)) |>
        mutate(across(where(is.double), ~ round(.x, 4)))

      # Appliquer les labels CMT si disponibles
      lbls <- cmt_labels()
      if (!is.null(lbls) && "CMT" %in% names(obs_display)) {
        obs_display <- obs_display |>
          mutate(CMT = ifelse(
            as.character(CMT) %in% names(lbls),
            paste0(lbls[as.character(CMT)], " (CMT=", CMT, ")"),
            as.character(CMT)
          ))
      }

      datatable(obs_display, rownames = FALSE,
                class = "stripe hover compact",
                options = list(pageLength = nrow(obs_display), dom = "t",
                               scrollX = TRUE))
    })

  })
}
