# =============================================================================
# mod_prior.R — Onglet Design Robuste ($PRIOR / $SIM TRUE=PRIOR)
# =============================================================================

mod_prior_ui <- function(id) {
  ns <- NS(id)
  tagList(uiOutput(ns("content")))
}

mod_prior_server <- function(id, summary_data, ctl_data = reactive(NULL),
                              all_runs = reactive(list())) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    output$content <- renderUI({
      summ  <- summary_data()
      prior <- ctl_data()

      has_summ  <- !is.null(summ) && !is.null(summ[["TIME"]])
      has_prior <- !is.null(prior) && isTRUE(prior$has_prior)

      if (!has_summ && !has_prior) {
        return(div(class = "alert alert-info", style = "border-radius:10px; margin:16px 0;",
          tags$strong("Robust Design"),
          tags$p(style = "margin:6px 0 0;",
            "Available when:",
            tags$ul(style = "margin:4px 0;",
              tags$li(tags$code("$PRIOR NWPRI"), " is present in the .ctl file"),
              tags$li(tags$code("summary.tab"), " generated by ",
                      tags$code("$SIM TRUE=PRIOR SUBPROB=1000"))
            )
          )
        ))
      }

      n_sub <- summ[["n_sub"]] %||% 1000L

      parts <- list()

      # -- Bandeau pedagogique ------------------------------------------------
      parts <- c(parts, list(
        div(class = "info-panel", style = "margin-bottom:16px;",
          tags$strong("Robust design principle"),
          tags$p(style = "margin:6px 0 0; font-size:.88rem;",
            "Sampling times are optimized independently for",
            tags$strong(paste0(n_sub, " parameter sets")),
            paste0("drawn from the prior ($SIM TRUE=PRIOR SUBPROB=", n_sub, ")."),
            "The [2.5% - 97.5%] ranges below indicate times that remain",
            "informative regardless of parametric uncertainty.",
            "Recommended procedure: choose times within these ranges, then",
            "re-evaluate the resulting design to check the efficiency loss."
          )
        )
      ))

      # -- Section A : Prior utilise ------------------------------------------
      if (has_prior) {
        parts <- c(parts, list(
          div(class = "param-table-wrap",
            p(class = "section-title", "Prior used ($PRIOR NWPRI)"),
            uiOutput(ns("prior_cards")),
            br(),
            DTOutput(ns("prior_thetap"))
          ),
          br()
        ))
      }

      # -- Section B : Distribution des temps robustes ------------------------
      if (has_summ) {
        parts <- c(parts, list(
          div(class = "plot-card",
            p(class = "section-title",
              paste0("Optimal times distribution over ", n_sub, " prior replications")),
            plotOutput(ns("robust_plot"), height = "380px")
          ),
          br(),
          div(class = "param-table-wrap",
            p(class = "section-title",
              HTML("Robust sampling time ranges &mdash;
                    <span style='color:#6b7280; font-size:.85em;'>
                    Columns: Mean | STD | RSTD(%) | 2.5% | 97.5%</span>")),
            p(style = "font-size:.82rem; color:#6b7280; margin:-4px 0 8px;",
              "Row 1 = TSTRAT 1, row 2 = TSTRAT 2, etc. (time 0 / dose excluded)."),
            DTOutput(ns("robust_table"))
          )
        ))
      }

      do.call(tagList, parts)
    })

    # -------------------------------------------------------------------------
    # Cartes Prior
    # -------------------------------------------------------------------------
    output$prior_cards <- renderUI({
      prior <- ctl_data(); req(prior, prior$has_prior)
      fluidRow(
        column(4, metric_card_v5("Type", "NWPRI",
                                 icon_name = "book", color = "#2563eb",
                                 sub = prior$raw_prior_line %||% "$PRIOR")),
        column(4, metric_card_v5("PLEV",
                                 if (isTRUE(!is.na(prior$plev))) prior$plev else "N/A",
                                 icon_name = "check-circle", color = "#7c3aed",
                                 sub = "Acceptance level")),
        column(4, metric_card_v5("THETAP", length(prior$thetap),
                                 icon_name = "sliders-h", color = "#16a34a",
                                 sub = "Parameters with prior"))
      )
    })

    # -------------------------------------------------------------------------
    # Table THETAP
    # -------------------------------------------------------------------------
    output$prior_thetap <- renderDT({
      prior <- ctl_data(); req(prior, prior$has_prior, length(prior$thetap) > 0)
      tp <- tibble(
        Parameter = paste0("THETA", seq_along(prior$thetap)),
        `Prior (THETAP)` = prior$thetap,
        `Prior SD`       = if (!is.null(prior$thetapv)) round(sqrt(diag(prior$thetapv)), 4) else NA_real_
      )
      datatable(tp, rownames = FALSE, class = "stripe hover compact",
                options = list(pageLength = 15, dom = "t"))
    })

    # -------------------------------------------------------------------------
    # Plot robuste (TIME mean +/- IC 95% vs IPRED mean +/- IC 95%)
    # -------------------------------------------------------------------------
    output$robust_plot <- renderPlot({
      summ <- summary_data(); req(summ)
      time_df  <- summ[["TIME"]];  req(time_df)
      ipred_df <- summ[["IPRED"]]; req(ipred_df)
      n_sub <- summ[["n_sub"]] %||% 1000L

      # Exclure la ligne dose (row 1, TIME=0)
      time_df  <- time_df[-1, , drop = FALSE]
      ipred_df <- ipred_df[-1, , drop = FALSE]

      lo_col_t <- if ("2.50%"  %in% names(time_df))  "2.50%"  else "Low"
      hi_col_t <- if ("97.50%" %in% names(time_df))  "97.50%" else "High"
      lo_col_i <- if ("2.50%"  %in% names(ipred_df)) "2.50%"  else "Low"
      hi_col_i <- if ("97.50%" %in% names(ipred_df)) "97.50%" else "High"

      plot_df <- tibble(
        tstrat     = paste0("TSTRAT ", seq_len(nrow(time_df))),
        time_mean  = time_df$Mean,
        time_lo    = time_df[[lo_col_t]],
        time_hi    = time_df[[hi_col_t]],
        ipred_mean = ipred_df$Mean,
        ipred_lo   = ipred_df[[lo_col_i]],
        ipred_hi   = ipred_df[[hi_col_i]]
      )

      p <- ggplot(plot_df, aes(x = time_mean, y = ipred_mean, label = tstrat)) +
        geom_ribbon(aes(ymin = ipred_lo, ymax = ipred_hi),
                    fill = "#3b82f6", alpha = 0.13) +
        geom_errorbarh(aes(xmin = time_lo, xmax = time_hi),
                       height = 0, color = "#6b7280", size = 0.5) +
        geom_point(size = 4, color = "#2563eb") +
        geom_line(size = 0.6, color = "#2563eb", alpha = 0.45) +
        geom_text(size = 3.2, color = "#374151", vjust = -1)

      # Multi-run overlay: comparison runs' mean predictions
      runs <- all_runs()
      if (length(runs) > 1L) {
        comp_overlays <- purrr::imap(runs[-1], function(r, rid) {
          if (is.null(r$tab_data)) return(NULL)
          comp_tab <- r$tab_data
          if (!("table_no" %in% names(comp_tab)) ||
              dplyr::n_distinct(comp_tab$table_no) <= 1L)
            return(NULL)
          comp_summ <- tryCatch(compute_robust_summary(comp_tab),
                                error = function(e) NULL)
          if (is.null(comp_summ) || is.null(comp_summ[["TIME"]]) ||
              is.null(comp_summ[["IPRED"]]))
            return(NULL)
          ct <- comp_summ[["TIME"]][-1, , drop = FALSE]
          ci <- comp_summ[["IPRED"]][-1, , drop = FALSE]
          if (nrow(ct) == 0L) return(NULL)
          tibble(time_mean = ct$Mean, ipred_mean = ci$Mean, run = rid)
        }) |> dplyr::bind_rows()

        if (nrow(comp_overlays) > 0L) {
          run_labels <- setNames(
            vapply(runs[-1], function(r) r$name, character(1L)),
            names(runs[-1]))
          run_colors <- setNames(
            vapply(names(runs[-1]), run_color, character(1L)),
            names(runs[-1]))
          p <- p +
            geom_line(data = comp_overlays,
                      aes(x = time_mean, y = ipred_mean, color = run),
                      inherit.aes = FALSE, size = 0.7, alpha = 0.6,
                      linetype = "dashed") +
            geom_point(data = comp_overlays,
                       aes(x = time_mean, y = ipred_mean, color = run),
                       inherit.aes = FALSE, size = 3, alpha = 0.8) +
            scale_color_manual(values = run_colors, labels = run_labels,
                               name = NULL)
        }
      }

      p +
        labs(
          title    = paste0("Mean prediction and 95% CI (", n_sub,
                            " prior replications)"),
          subtitle = "Horizontal bars = 95% CI of times  |  Ribbon = 95% CI of IPRED",
          x        = "Time (h) -- Mean +/- 95% CI",
          y        = "IPRED -- Mean +/- 95% CI"
        ) +
        theme_bw(base_size = 11) +
        theme(panel.grid.minor = element_blank())
    }, res = 110)

    # -------------------------------------------------------------------------
    # Table des plages robustes (TIME uniquement, filtre dose)
    # -------------------------------------------------------------------------
    output$robust_table <- renderDT({
      summ <- summary_data(); req(summ)
      time_df <- summ[["TIME"]]; req(time_df)

      # Exclure la ligne dose (row 1)
      df <- time_df[-1, , drop = FALSE]

      lo_col <- if ("2.50%"  %in% names(df)) "2.50%"  else "Low"
      hi_col <- if ("97.50%" %in% names(df)) "97.50%" else "High"

      display <- tibble(
        TSTRAT        = seq_len(nrow(df)),
        `Mean (h)`    = round(df$Mean, 3),
        `STD`         = round(df$STD,  3),
        `RSTD (%)`    = round(df$RSTD, 1),
        `2.5% (h)`    = round(df[[lo_col]], 3),
        `97.5% (h)`   = round(df[[hi_col]], 3),
        `Suggested range` = paste0(
          "[", round(floor(df[[lo_col]] * 4) / 4, 2),
          " \u2013 ", round(ceiling(df[[hi_col]] * 4) / 4, 2), "]"
        )
      )

      datatable(display, rownames = FALSE, class = "stripe hover compact",
                options = list(dom = "t", ordering = FALSE)) |>
        formatStyle("RSTD (%)",
          color = styleInterval(c(25, 50), c("#16a34a", "#d97706", "#dc2626")),
          fontWeight = "bold"
        ) |>
        formatStyle("Suggested range",
          fontWeight = "bold", color = "#2563eb"
        )
    })
  })
}
